// ==========================================
// DADOS HARDCODED ATUALIZADOS (IMAGENS E VIDEOS REAIS)
// ==========================================

const PLANTS = [
    { id: 1, name: "Costela de Adão", nick: "Monstera Deliciosa", origin: "Florestas Tropicais do México", price: 89.90, difficulty: "Fácil", light: "Meia sombra", water: "2x por semana", brotos: 45, imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=600", tag: "Popular", desc: "Suas folhas recortadas icônicas são desenhadas naturalmente para deixar o vento passante e a luz chegar às folhas de baixo.", curiosity: "Na era vitoriana, ter uma Monstera em sua sala de estar indicava alta classe social e espírito de exploração botânica." },
    { id: 2, name: "Ficus Lyrata", nick: "Figueira-Lira", origin: "Oeste da África", price: 180.00, difficulty: "Média", light: "Muita luz indireta", water: "1x por semana", brotos: 90, imageUrl: "https://images.unsplash.com/photo-1597055181300-e3633a207518?q=80&w=600", tag: "Rara", desc: "Uma planta majestosa com folhas grandes em formato de lira, altamente decorativa e imponente.", curiosity: "Em seu habitat natural africano, ela pode crescer como uma planta epífita, germinando no topo de outras árvores." },
    { id: 3, name: "Espada de São Jorge", nick: "Sansevieria Trifasciata", origin: "África Ocidental", price: 45.00, difficulty: "Fácil", light: "Qualquer luz", water: "1x a cada 15 dias", brotos: 20, imageUrl: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?q=80&w=600", tag: "Resistente", desc: "Folhas verticais rígidas e coriáceas. Extremamente durável e limpa o ar de toxinas comuns.", curiosity: "A NASA a listou oficialmente como uma das melhores plantas para purificar o ar dentro de naves e estações espaciais." },
    { id: 4, name: "Orquídea Mariposa", nick: "Phalaenopsis", origin: "Sudeste Asiático", price: 75.00, difficulty: "Média", light: "Luz filtrada", water: "1x por semana", brotos: 40, imageUrl: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?q=80&w=600", tag: "Clássica", desc: "Flores delicadas que lembram o voo de mariposas. Perfeitas para ambientes internos iluminados.", curiosity: "Na China antiga, as orquídeas eram cultivadas pelo próprio filósofo Confúcio, que as chamava de 'Rainhas das Fragrâncias'." },
    { id: 5, name: "Planta Néon", nick: "Pothos Neon", origin: "Ilhas Salomão", price: 55.00, difficulty: "Fácil", light: "Média luz", water: "2x por semana", brotos: 25, imageUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=600", tag: "Pendente", desc: "Folhagem de tom verde-limão vibrante que cresce em cascatas exuberantes.", curiosity: "É uma das poucas plantas de casa que sobrevive muito bem cultivada diretamente na água por anos." },
    { id: 6, name: "Begônia Maculata", nick: "Begonia Tamaya", origin: "Florestas Tropicais do Brasil", price: 120.00, difficulty: "Especialista", light: "Luz indireta filtrada", water: "2x por semana", brotos: 60, imageUrl: "https://images.unsplash.com/photo-1612360566326-8098b67f10b7?q=80&w=600", tag: "Colecionador", desc: "Folhas verde-oliva escuras cobertas com bolinhas brancas perfeitas e verso vermelho-sangue.", curiosity: "Diz a lenda fashion que o designer Christian Louboutin se inspirou no verso vermelho da Begônia Maculata para criar suas icônicas solas de sapato." },
    { id: 7, name: "Calathea Triostar", nick: "Stromanthe Thalia", origin: "América do Sul", price: 95.00, difficulty: "Especialista", light: "Sombra úmida", water: "3x por semana", brotos: 50, imageUrl: "https://images.unsplash.com/photo-1545167622-3a6ac756afa4?q=80&w=600", tag: "Exótica", desc: "Folhas pintadas à mão pela natureza em tons de rosa, creme e verde.", curiosity: "Pertence à família das 'plantas rezadeiras': à noite suas folhas se levantam verticalmente como mãos em oração." },
    { id: 8, name: "Cacto Macarrão", nick: "Rhipsalis Baccifera", origin: "América Central e África", price: 40.00, difficulty: "Fácil", light: "Meia sombra", water: "1x por semana", brotos: 20, imageUrl: "https://images.unsplash.com/photo-1509423424749-37312a3d4643?q=80&w=600", tag: "Diferente", desc: "Um cacto que quebra as regras: não tem espinhos, adora umidade e vive pendurado em árvores.", curiosity: "É a única espécie de cacto nativa encontrada naturalmente fora das Américas, cruzando o Atlântico séculos atrás." },
    { id: 9, name: "Zamioculca", nick: "Zamioculcas Zamiifolia", origin: "África Oriental", price: 65.00, difficulty: "Fácil", light: "Sombra total a Sol", water: "1x a cada 20 dias", brotos: 30, imageUrl: "https://images.unsplash.com/photo-1632205510651-7f938c4bdf45?q=80&w=600", tag: "Escritório", desc: "Folhas enceradas ultra brilhantes que parecem artificiais. Sobrevive a grandes períodos de negligência.", curiosity: "No Sudeste Asiático, ela é chamada de 'Árvore de Ouro' por atrair prosperidade e estabilidade financeira onde é colocada." }
];

const COURSES = [
    { id: 1, emoji: "🌱", title: "Jardinagem para Iniciantes", level: "Iniciante", duration: "45 min", lessons: 5, desc: "Aprenda a não matar mais nenhuma planta. Conceitos básicos sobre rega, luz e escolha do vaso ideal.", youtubeUrl: "https://www.youtube.com/watch?v=A8vGf_vXp2Q", topics: ["Como escolher a primeira planta", "O teste do dedo: quando regar", "Tipos de vasos e drenagem correta", "Identificando excesso ou falta de sol"] },
    { id: 2, emoji: "✂️", title: "Arte da Propagação e Mudas", level: "Iniciante", duration: "1h 15min", lessons: 6, desc: "Multiplique seu jardim de graça fazendo mudas por estacas de nós, folhas ou divisão de raízes.", youtubeUrl: "https://www.youtube.com/watch?v=FjIuKxPnvpM", topics: ["Onde cortar: localizando o nó", "Enraizamento na água vs na terra", "Cuidados com os brotos bebês", "Hormônios enraizadores naturais"] },
    { id: 3, emoji: "🪵", title: "Substratos e Solos Perfeitos", level: "Intermediário", duration: "50 min", lessons: 4, desc: "Esqueça a terra preta comum. Crie misturas aeradas e nutritivas específicas para cada espécie.", youtubeUrl: "https://www.youtube.com/watch?v=E-4W-02YfWw", topics: ["Perlita, fibra de coco e casca de pínus", "Montando solo para Monstera e Aráceas", "Drenagem perfeita para Cactos e Suculentas", "Adubação orgânica básica"] },
    { id: 4, emoji: "🦟", title: "Guia de Combate a Pragas", level: "Intermediário", duration: "1h", lessons: 7, desc: "Aprenda a identificar e eliminar cochonilhas, ácaros e fungos usando receitas 100% caseiras.", youtubeUrl: "https://www.youtube.com/watch?v=3R-gKq9K75w", topics: ["Identificação visual de pragas comuns", "O poder do Óleo de Neem e Sabão de Coco", "Como tratar fungos nas folhas", "Isolamento de plantas doentes"] },
    { id: 5, emoji: "🪴", title: "Guia de Cultivo da Monstera", level: "Intermediário", duration: "35 min", lessons: 3, desc: "Segredos para fazer sua Costela de Adão crescer folhas gigantescas com fenações lindas.", youtubeUrl: "https://www.youtube.com/watch?v=2n5q80u0g3I", topics: ["Uso de tutores de musgo", "Estímulo para folhas maiores", "Luz perfeita para Monsteras"] },
    { id: 6, emoji: "🔬", title: "Botânica Científica Prática", level: "Avançado", duration: "2h", lessons: 10, desc: "Entenda o funcionamento da fotossíntese profunda, respiração celular e o ciclo de nutrientes do solo.", youtubeUrl: "https://www.youtube.com/watch?v=Xv6O_K1N_4I", topics: ["Fisiologia vegetal avançada", "Macronutrientes e Micronutrientes", "Níveis de pH do solo e absorção", "Como ler as folhas: deficiências químicas"] },
    { id: 7, emoji: "🏜️", title: "Florestas de Suculentas Raras", level: "Avançado", duration: "1h 40min", lessons: 8, desc: "Aprenda as técnicas avançadas de estresse controlado para colorir e colecionar espécies raras de desertos.", youtubeUrl: "https://www.youtube.com/watch?v=F
